

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db_pg:
    container_name: pg_db
    # image: postgres:18
    build:
      context: ./source/db_pg
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 4
    ports:
      - 5432:5432
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql
      - ./backup/pg:/var/backups

  db_vec:
    container_name: db_vec
    image: pgvector/pgvector:pg18-trixie
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres

  db_pgai: # pgvectorscale
    container_name: db_pgai
    # image: timescale/timescaledb-ha:latest-pg18
    image: timescale/timescaledb:latest-pg18
    restart: unless-stopped
    ports:
      - 5434:5432
    env_file:
     - path: .env
       required: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: /pgdata
    volumes:
      - ./pgai/db:/pgdata

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  pgdata:

networks:
  default:
    name: melearningrag_network